# Generated by Django 2.2.1 on 2019-05-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
